// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// callModel
List callModel(NumericMatrix environment, unsigned int iterations, int maxDuration, NumericMatrix parameters, unsigned int randomSeed, int output, IntegerVector TimeAtObservation, NumericVector upperleft, double environmentResolution, Rcpp::CharacterVector filename, double startTime, int startDayOfYear, double solarLatitude, double solarLongitude);
RcppExport SEXP _LOSim_callModel(SEXP environmentSEXP, SEXP iterationsSEXP, SEXP maxDurationSEXP, SEXP parametersSEXP, SEXP randomSeedSEXP, SEXP outputSEXP, SEXP TimeAtObservationSEXP, SEXP upperleftSEXP, SEXP environmentResolutionSEXP, SEXP filenameSEXP, SEXP startTimeSEXP, SEXP startDayOfYearSEXP, SEXP solarLatitudeSEXP, SEXP solarLongitudeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type environment(environmentSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type iterations(iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type maxDuration(maxDurationSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< unsigned int >::type randomSeed(randomSeedSEXP);
    Rcpp::traits::input_parameter< int >::type output(outputSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type TimeAtObservation(TimeAtObservationSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upperleft(upperleftSEXP);
    Rcpp::traits::input_parameter< double >::type environmentResolution(environmentResolutionSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< double >::type startTime(startTimeSEXP);
    Rcpp::traits::input_parameter< int >::type startDayOfYear(startDayOfYearSEXP);
    Rcpp::traits::input_parameter< double >::type solarLatitude(solarLatitudeSEXP);
    Rcpp::traits::input_parameter< double >::type solarLongitude(solarLongitudeSEXP);
    rcpp_result_gen = Rcpp::wrap(callModel(environment, iterations, maxDuration, parameters, randomSeed, output, TimeAtObservation, upperleft, environmentResolution, filename, startTime, startDayOfYear, solarLatitude, solarLongitude));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LOSim_callModel", (DL_FUNC) &_LOSim_callModel, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_LOSim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
