# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

callModel <- function(environment, iterations, maxDuration, parameters, randomSeed, output, TimeAtObservation, upperleft, environmentResolution, filename, startTime, startDayOfYear, solarLatitude, solarLongitude) {
    .Call('_LOSim_callModel', PACKAGE = 'LOSim', environment, iterations, maxDuration, parameters, randomSeed, output, TimeAtObservation, upperleft, environmentResolution, filename, startTime, startDayOfYear, solarLatitude, solarLongitude)
}

